// <auto-generated />
using System;
using Amaris.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amaris.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260227220730_AddServiceEntity")]
    partial class AddServiceEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Amaris.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Address = "Calle 10 #5-20",
                            City = "Bogotá",
                            Name = "Sucursal Centro"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Address = "Av. 19 #120-45",
                            City = "Bogotá",
                            Name = "Sucursal Norte"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Address = "Calle 45 Sur #80-10",
                            City = "Bogotá",
                            Name = "Sucursal Sur"
                        });
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Description = "Operaciones de caja general",
                            Name = "Ventanilla / Caja"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Description = "Asesoría para clientes comerciales",
                            Name = "Asesoría Comercial"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Description = "Tarjetas, créditos, cuentas, CDT",
                            Name = "Asesoría en Productos"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Description = "Atención preferencial",
                            Name = "Atención Prioritaria"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Description = "Pagos de servicios y retiros",
                            Name = "Pagos / Retiros"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Description = "Consultas e información general",
                            Name = "Información General"
                        });
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateActivation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdLocation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TurnCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdLocation");

                    b.HasIndex("ServiceId");

                    b.HasIndex("Identification", "DateCreation");

                    b.ToTable("Turn");
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Turn", b =>
                {
                    b.HasOne("Amaris.Domain.Entities.Location", "Location")
                        .WithMany("Turns")
                        .HasForeignKey("IdLocation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Amaris.Domain.Entities.Service", "Service")
                        .WithMany("Turns")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Location", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Amaris.Domain.Entities.Service", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
